version: "3.7"
services:

## Airsonic - Music Server
  # Login: admin / admin

  ## Suggested procedure to create your database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE airsonic CHARACTER SET = utf8 COLLATE = utf8_general_ci;
    # GRANT ALL PRIVILEGES ON airsonic.* TO 'airsonic'@'airsonic.traefik_proxy' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  airsonic2:
    container_name: airsonic2
    image: linuxserver/airsonic
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "4040:4040"
    volumes:
      - /mnt/storage/music/music:/music:ro
      - $USERDIR/docker/airsonic/podcasts:/podcasts
      - $USERDIR/docker/airsonic/playlists:/playlists
      - $USERDIR/docker/airsonic2/config:/config
#      - $USERDIR/docker/airsonic2/logging:/app/airsonic/config #Used to change log level for debugging
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - JAVA_OPTS=-Dserver.use-forward-headers=true

networks:
  traefik_proxy:
    external: true
