version: "3.7"
services:

## Organizr - Unified Server Web Interface

  ## Still need to add allow from header...

  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - "1180:80"
    volumes:
      - ${USERDIR}/docker/organizr:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.organizr-rtr.entrypoints=https"
#      - "traefik.http.routers.organizr-rtr.rule=Host(`$DOMAIN`,`www.$DOMAIN`)"
      - "traefik.http.routers.organizr-rtr.rule=Host(`organizr.$DOMAINNAME`)"
      - "traefik.http.routers.organizr-rtr.tls=true"
      - "traefik.http.routers.organizr-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.organizr-rtr.middlewares=secure-chain@file,organizr-headers"
#      - "traefik.http.middlewares.organizr-headers.headers.customframeoptionsvalue=allow-from https:$DOMAIN" # This option overrides FrameDeny
      - "traefik.http.middlewares.organizr-headers.headers.customframeoptionsvalue=allow-from https:$DOMAINNAME" # This option overrides FrameDeny
      ## HTTP Services
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.organizr-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
