version: "3.7"
services:

## Postgres - Database

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "5432:5432"
    volumes:
      - $USERDIR/docker/postgres/postgres:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=$PG_ROOT_PASSWORD

## PGAdmin - Postgres Admin Tool

  ## Haven't got this one working quite yet...

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    networks:
      - traefik_proxy
    ports:
      - "5050:80"
    volumes:
      - $USERDIR/docker/postgres/pgadmin:/var/lib/pgadmin
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGADMIN_DEFAULT_EMAIL=$MY_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$MY_PASSWORD
      - PGADMIN_CONFIG_APP_NAME="CVJoint's PGAdmin"
      - PGADMIN_CONFIG_DEFAULT_SERVER="0.0.0.0"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pgadmin-rtr.entrypoints=https"
      - "traefik.http.routers.pgadmin-rtr.rule=Host(`pgadmin.$DOMAINNAME`)"
      - "traefik.http.routers.pgadmin-rtr.tls=true"
      - "traefik.http.routers.pgadmin-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.pgadmin-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.pgadmin-rtr.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=80"


networks:
  traefik_proxy:
    external: true
